### ISSUE TITLE
`TypeError: value.match is not a function`

### ISSUE THREAD

**Issue by Adamkadaban** [pietrobolcato/action-read-yaml#14]
I believe I'm using the exact example code provided, but I'm getting the following error
![image](https://github.com/pietrobolcato/action-read-yaml/assets/34610663/1dd834c5-7c99-448a-a7ab-ad6084ab9526)

```yaml

jobs:
  read-yaml:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: read-yaml-file
        uses: pietrobolcato/action-read-yaml@1.0.0
        id: read_action_js
        with:
          config: ${{ github.workspace }}/config.yaml
```

```yaml
name: example
environment:
  name: example
  permissions:
    - name: example
      permission: read
    - name: example2
      permission: write
deployment:
  code:
    source:
      libs: path/to/libs
      entry: path/to/entry
```
