### ISSUE TITLE
Can't access item in json

### ISSUE THREAD

**Issue by kotowick** [pietrobolcato/action-read-yaml#7]
So I am trying to use this. I have it running in one job, and using the output method so I can access it in another job.

Now, I can echo the data in the second job. However, I cannot seem to find a way to access any elements inside.

```
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      config: ${{ toJson(steps.config.outputs) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: read-config
        uses: pietrobolcato/action-read-yaml@1.1.0
        id: config
        with:
          config: ${{ github.workspace }}/deployment/dev/ca-central-1/config.yaml
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(steps.config.outputs) }}
        run: echo "$JOB_CONTEXT"


build:
    name: Build
    runs-on: ubuntu-latest
    needs: setup
    env:
      CONFIG: ${{ needs.setup.outputs.config }}

    steps:
      - name: Dump job context
         env:
           JOB_CONTEXT: ${{ needs.setup.outputs.config }}
         run: echo "${{  env.JOB_CONTEXT['aws_default_region'] }}"
```

How can I access "aws_default_region"? I tried 100 ways.
