### ISSUE TITLE
Unable to print an array value

### ISSUE THREAD

**Issue by bh3r1th** [pietrobolcato/action-read-yaml#8]
My input YAML file has these values.
```
domain_name: domain
env_name: dev
dataset_id: ["dataset_name1", "dataset_name2"]
```

This code is printing an empty value for dataset_id
```
- name: Read YAML file
        id: read-yaml-file
        uses: pietrobolcato/action-read-yaml@1.1.0
        with:
          config: ${{ github.workspace }}/${{ steps.run_git_diff.outputs.file_name }}
      - name: Get dataset name
        id: get_ds_name
        run: |
          echo "dataset_id=${{ steps.read-yaml-file.outputs['dataset_id'] }}"
```

Can someone tell me why?
